[workspace]
channels = ["conda-forge"]
name = "marimo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10.0,<3.14"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
marimo = ">=0.17.8, <0.18"
nbformat = ">=5.10.4, <6"
